name: artifactory-oss_${ARTIFACTORY_VERSION}
version: '3'
services:
  artifactory:
    image: ${DOCKER_REGISTRY}/jfrog/artifactory-oss:${ARTIFACTORY_VERSION}
    container_name: artifactory-oss_${ARTIFACTORY_VERSION}
    environment:
      - JF_ROUTER_ENTRYPOINTS_EXTERNALPORT=${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - TZ=${TIME_ZONE}
    ports:
      - ${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - 8081:8081
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
      # - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    networks:
      - artifactory
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 2gb
  nginx:
    image: ${DOCKER_REGISTRY}/jfrog/nginx-artifactory:${ARTIFACTORY_VERSION}
    container_name: artifactory-oss-nginx_${ARTIFACTORY_VERSION}
    depends_on:
      - artifactory
    network_mode: service:artifactory
    volumes:
      - nginx_data:/var/opt/jfrog/nginx
      # - /etc/localtime:/etc/localtime:ro
    environment:
      - ART_BASE_URL=http://localhost:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
      - NGINX_LOG_ROTATE_COUNT=${NGINX_LOG_ROTATE_COUNT}
      - NGINX_LOG_ROTATE_SIZE=${NGINX_LOG_ROTATE_SIZE}
      - SSL=false
      - TZ=${TIME_ZONE}
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: artifactory-oss-postgresql_${POSTGRES_VERSION}
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=1234
      - TZ=${TIME_ZONE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - artifactory
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
networks:
  artifactory:
    name: artifactory
volumes:
  artifactory_data:
    name: artifactory_data
  nginx_data:
    name: artifactory-nginx_data
  postgres_data:
    name: artifactory-postgres_data